import { ProposalSegmentFields } from "src/models/segment/proposal/proposalSegmentFields";
import { DateFormats } from "src/utils/date-utils";
import { format as dateFormat } from "date-fns";

export function getProposalSegmentFields(proposal: any){
    let proposalObject: ProposalSegmentFields = {
        phone: proposal?.user?.phone,
        user_pincode_journey: proposal?.user?.pincode,
        external_cng_kit: proposal?.vehicle?.is_external_cng_kit,
        registration_number: proposal?.vehicle?.registration_number,
        make_name: proposal?.vehicle?.make_name,
        model_name: proposal?.vehicle?.model_name,
        variant_id: proposal?.vehicle?.variant_ekey,
        variant_name: proposal?.vehicle?.variant_name,
        engine_cc: proposal?.vehicle?.cc?.toString(),
        fuel_type: proposal?.vehicle?.fuel_type,
        registration_year: proposal?.vehicle?.registration_year,
        registration_month: proposal?.vehicle?.registration_month,
        is_commercial: proposal?.vehicle?.is_commercial,
        chassis_number: proposal?.vehicle?.chassis_number,
        engine_number: proposal?.vehicle?.engine_number,
        rto_zone: proposal?.vehicle?.rto_code,
        is_expired: proposal?.vehicle?.previous_policy?.is_expired,
        previous_policy_type: proposal?.vehicle?.previous_policy?.policy_type,
        previous_policy_expiry_bucket: proposal?.vehicle?.previous_policy?.policy_status,
        previous_insurer: proposal?.vehicle?.previous_policy?.insurer_name,
        previous_policy_expiry_date: proposal?.vehicle?.previous_policy?.expiry_datev1 ? `${dateFormat(new Date(proposal?.vehicle?.previous_policy?.expiry_datev1),DateFormats.ISO_DATE)}T05:30:00+05:30` : proposal?.vehicle?.previous_policy?.expiry_datev1,
        previous_od_expiry_date: proposal?.vehicle?.previous_policy?.own_damage_policy_expiry_date ? `${dateFormat(new Date(proposal?.vehicle?.previous_policy?.own_damage_policy_expiry_date),DateFormats.ISO_DATE)}T05:30:00+05:30` : proposal?.vehicle?.previous_policy?.own_damage_policy_expiry_date,
        previous_tp_expiry_date: proposal?.vehicle?.previous_policy?.third_party_policy_expiry_date ? `${dateFormat(new Date(proposal?.vehicle?.previous_policy?.third_party_policy_expiry_date),DateFormats.ISO_DATE)}T05:30:00+05:30` : proposal?.vehicle?.previous_policy?.third_party_policy_expiry_date,
        previous_ncb: proposal?.vehicle?.previous_policy?.previous_ncb,
        previous_idv: proposal?.vehicle?.previous_policy?.previous_idv,
        last_year_claim_flag: proposal?.vehicle?.previous_policy?.previous_policy_claim_answer,
        proposal_id: proposal?.ekey,
        current_ncb: proposal?.policy_attributes?.ncb,
        is_inspection_reqd: proposal?.context?.pi_required,
        last_claim_year: proposal?.vehicle?.previous_policy?.last_claim_year,
        user_name: proposal?.user?.name,
        email: proposal?.user?.email,
        pan_number: proposal?.user?.pan_number,
        journey_version: 'v3',
        logged_in: proposal?.context?.mobile_verified ?? false,
        asset_type: proposal?.product,

        is_registration_number_autofilled: proposal?.vehicle?.registration_number ? true : false,
        is_make_autofilled: proposal?.vehicle?.make_name ? true : false,
        is_model_autofilled: proposal?.vehicle?.make_name ? true : false,
        is_variant_autofilled: proposal?.vehicle?.model_name ? true : false,
        is_engine_number_autofilled: proposal?.vehicle?.engine_number ? true : false,
        is_chassis_number_autofilled: proposal?.vehicle?.chassis_number ? true : false,
        is_registration_date_autofilled: proposal?.vehicle?.registration_month && proposal?.vehicle?.registration_year ? true : false,
        is_previous_policy_type_autofilled: proposal?.vehicle?.previous_policy?.policy_type && proposal?.vehicle?.previous_policy?.policy_type_source != 'user' ? true : false,
        is_previous_policy_expiry_date_autofilled: proposal?.vehicle?.previous_policy?.policy_expiry_date_source != 'user' ? true : false,
        is_previous_insurer_autofilled: proposal?.vehicle?.previous_policy?.insurer_name && proposal?.vehicle?.previous_policy?.insurer_name!='others' ? true : false,
        is_previous_idv_autofilled: proposal?.vehicle?.previous_policy?.previous_idv ? true : false,
        is_previous_ncb_autofilled: proposal?.vehicle?.previous_policy?.ncb_source != 'user' ? true : false,
        is_last_year_claim_flag_autofilled: proposal?.suggested_attributes?.iib_suggestions?.suggested_last_claim_year ? true : false,
        is_phone_number_autofilled: proposal?.user?.phone ? true : false,
        is_pincode_autofilled: proposal?.user?.pincode ? true : false,
        is_rc_name_autofilled: proposal?.vehicle?.rc_data_populated ? true : false,
    }
    return proposalObject;
}